### ISSUE TITLE
Has the minimum PHP Requirements changed to PHP 7.1?

### ISSUE THREAD

**Issue by forikal-uk** [forikal-uk/ping-drive#2]
## Steps to recreate

I am [taking notes as I get the code working for the first time](https://github.com/forikal-uk/ping-drive/issues/1#issuecomment-393911274).

The act of migrating some of our code into the [xml-authoring-library (shared library)](https://github.com/forikal-uk/xml-authoring-library) project triggered discussion about whether we should increase minimum PHP  to version 7.1.

It was allowed because we have control over our user's PHP installations. 

## What occurs

I note the [requirements](https://github.com/forikal-uk/ping-drive#requirements) say:

> PHP 5.5.9 or newer

## What is expected

Does this need to say PHP 7.1 or is this aspect of the project still "PHP 5.5.9 or higher"?

**Comment by Finesse** [comment]
@forikal-uk 

> Does this need to say PHP 7.1 or is this aspect of the project still "PHP 5.5.9 or higher"?

I finished the command and reported you before we decide to update to PHP 7.1. I will update soon.
