### ISSUE TITLE
Use of the word `command` in standalone install instructions

### ISSUE THREAD

**Issue by forikal-uk** [forikal-uk/ping-drive#3]
## Steps to Recreate

Look at the [instructions to install as a standalone project](https://github.com/forikal-uk/ping-drive/blob/master/README.md#as-a-standalone-project).

## What occurs

It says:

> ### As a standalone project
> 
> You can install the command as a standalone application. Open a terminal and run:
> 
> ```bash
> composer create-project forikal-uk/ping-drive command
> 
> # or 
> 
> git clone https://github.com/forikal-uk/ping-drive.git command
> composer install -d command
> ```
> 
> Replace `command` with a path to a directory where the command must be installed. In this case the command is started by running:
> 
> ```bash
> php command/ping-drive ...
> ```

### What I expect

I am wondering if the word `command` is best here. I understood that variable to reference `directory`.

I have never used this technique before. Maybe command is the correct word if we wanna just collect a selection of commands in one place.

--------

[Here are my notes as I experienced the issue.
](https://github.com/forikal-uk/ping-drive/issues/1#issuecomment-393918189)

Is this a pattern borrowed from some task runner or something? I quite like it.

**Comment by forikal-uk** [comment]
I am not sure if this is a bug or good. I just added the issue here so I don't forget it.

**Comment by Finesse** [comment]
@forikal-uk I agree with you. Changing `command` to `<directoryName>` makes the manual clearer.

**Comment by john-arcus** [comment]
Thanks.
