### ISSUE TITLE
Installation as a standalone project : `Could not find package forikal-uk/ping-drive with stability stable.`

### ISSUE THREAD

**Issue by forikal-uk** [forikal-uk/ping-drive#4]
## Steps to Recreate

Look at the [instructions to install as a standalone project](https://github.com/forikal-uk/ping-drive/blob/master/README.md#as-a-standalone-project).

I go to my projects folder 

```bash
$ pwd
/Users/jw/Documents/Projects/XmlAuthoring
```

Create a directory as destination.

```bash
$ mkdir ping-drive
```

Then get composer to create the project:

```bash
$ composer create-project forikal-uk/ping-drive ping-drive

```

## What occurs

Results in:

```bash
                                                                      
  [InvalidArgumentException]                                           
  Could not find package forikal-uk/ping-drive with stability stable.                                                                         

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```
## Expected

I expect no errors.

--------

[Here are my notes as I experienced the issue.
](https://github.com/forikal-uk/ping-drive/issues/1#issuecomment-393918189)

**Comment by forikal-uk** [comment]
Maybe this can be fixed by pushing a new tag to packagist or adding a line into the `composer.json` ?

**Comment by Finesse** [comment]
A repository needs to be [published to Packagist](https://packagist.org/packages/submit) to be available through Composer.

You have published the repository so the error doesn't occur anymore and the issue is resolved.

**Comment by john-arcus** [comment]
Thanks.
