### ISSUE TITLE
require_once fail on autoload when used as project dependency

### ISSUE THREAD

**Issue by forikal-uk** [forikal-uk/ping-drive#5]
## Steps to recreate

I was following the README instructions and Installing as a project dependency.

See my detailed notes here.

I ran the command.

## What was expected

I expected to see the command's help page show.

## What happened

I got an error

```
$ php vendor/bin/ping-drive  --help

Warning: require_once(/Users/x/Documents/Projects/XmlAuthoring/ping-parent/vendor/forikal-uk/ping-drive/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/x/Documents/Projects/XmlAuthoring/ping-parent/vendor/forikal-uk/ping-drive/bin/ping-drive on line 4

Fatal error: require_once(): Failed opening required '/Users/x/Documents/Projects/XmlAuthoring/ping-parent/vendor/forikal-uk/ping-drive/bin/../vendor/autoload.php' (include_path='.:') in /Users/jw/Documents/Projects/XmlAuthoring/ping-parent/vendor/forikal-uk/ping-drive/bin/ping-drive on line 4
```

----------

# Notes:

- I did not run the steps in the context of [xml-authoring-tools](https://github.com/forikal-uk/xml-authoring-tools) project (which is the context that matters most). I was blindly following the steps on this projects README file > [Installing as a project dependency](https://github.com/forikal-uk/ping-drive/blob/master/README.md#installing-as-a-project-dependency) - so the docs may need updating instead of the code.

- If we fix this for the project dependency installation it might break the code for the standalone installation.

- I am sure this is a very common bug and many have been here. There is probably some standard Symfony practice to ensure that this is fixed elegantly.

**Comment by Finesse** [comment]
@forikal-uk Fixed. Update the project (`composer update`) and run the command one more time.
